# -*- coding: utf-8 -*-
"""taitanic_deploy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VFToUnaIADbQ0rhzwEaHfkGA9heoz4uj
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# 1. تحميل الموديل (تأكد أن الاسم مطابق لملفك)
model = joblib.load("titanic_project.pkl")

st.title("🚢 Titanic Survival Prediction")
st.write("أدخل بيانات الراكب لمعرفة هل كان سينجو أم لا!")

# 2. إدخال البيانات (المدخلات الرقمية)
pclass = st.selectbox("Passenger Class (Pclass)", [1, 2, 3])
age = st.number_input("Age", min_value=0, max_value=100, value=25)
sibsp = st.number_input("Siblings/Spouses Aboard (SibSp)", min_value=0, max_value=10, value=0)
parch = st.number_input("Parents/Children Aboard (Parch)", min_value=0, max_value=10, value=0)
fare = st.number_input("Fare", min_value=0.0, value=10.0)

# 3. إدخال البيانات (المدخلات النصية)
sex = st.selectbox("Sex", ["male", "female"])
embarked = st.selectbox("Embarked", ["S", "C", "Q"])

# 4. زر التوقع
if st.button("Predict Survival 🔍"):
    # إنشاء Dictionary بالبيانات
    input_dict = {
        "Pclass": [pclass],
        "Sex": [sex],
        "Age": [age],
        "SibSp": [sibsp],
        "Parch": [parch],
        "Fare": [fare],
        "Embarked": [embarked]
    }

    # تحويل الـ Dictionary لـ DataFrame
    input_df = pd.DataFrame(input_dict)


    # عمل التوقع
    prediction = model.predict(input_df)

    # إظهار النتيجة
    if prediction[0] == 1:
        st.success("✅ الناكب نجا (Survived)")
    else:
        st.error("❌ للأسف، الراكب لم ينجُ (Not Survived)")